import { IRoute } from '@/utils/interfaces';

const workspaceRoutes: Array<IRoute> = [
    {
        name: 'workspace',
        title: 'Workspace',
        url: '/workspace',
        iconName: 'briefcase',
        action: 'navigate',
        isAuth: true,
        params: [],
        content: { collapsed: false },
        subroutes: [
            {
                name: 'my-hackathons',
                title: 'My Hackathons',
                iconName: 'trophy',
                url: '/hackathon',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                name: 'my-challenges',
                title: 'My Challenges',
                iconName: 'zap',
                url: '/challenge',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                name: 'my-projects',
                title: 'My Projects',
                iconName: 'folder',
                url: '/apprenticeship',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
        ],

        inroutes: [
            {
                route: 'workspace',
                parent: 'my-hackathons',
                name: 'create-hackathon',
                title: 'Host a Hackathon',
                url: '/create',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-hackathons',
                name: 'hackathon-details',
                title: 'Hackathon Details',
                url: '/:slug',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-hackathons',
                name: 'edit-hackathon',
                title: 'Edit Hackathon',
                url: '/:slug/edit',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-projects',
                name: 'create-project',
                title: 'New Project',
                url: '/create',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-projects',
                name: 'project-details',
                title: 'Project Details',
                url: '/:slug',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-projects',
                name: 'project-editor',
                title: 'Edit Project',
                url: '/:slug/edit',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-challenges',
                name: 'create-challenge',
                title: 'New Challenge',
                url: '/create',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-challenges',
                name: 'challenge-details',
                title: 'Challenge Details',
                url: '/:slug',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-challenges',
                name: 'edit-challenge',
                title: 'Edit Challenge',
                url: '/:slug/edit',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
        ],
    },
];

export default workspaceRoutes;
